/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml.to.java;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JCheckBox;
import java.awt.Font;

/**
 *
 * @author User
 */
public class EnterField extends javax.swing.JFrame {
	static boolean gett = false;

    /**
     * Creates new form EnterField
     */
    public EnterField() {
        initComponents();
           }
    
    public EnterField(String s) {
        initComponents();
        //String h = "enter ";
        //String g = h+s ;
        
        lblNewLabel.setText(s+" ");
        
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        returnType = new javax.swing.JLabel();
        accessModifier = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        enterFiledDetails = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Name.setText("Name");

        returnType.setText("Return Type:");

        accessModifier.setText("Acces Modifier: ");

        ok.setText("OK & EXIT");
        ok.setVisible(false);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
                okActionPerformed(evt);
            }
        });

        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        enterFiledDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterFiledDetails.setText("Enter Field");

        jButton1.setText("add get/set?");
        jButton1.setVisible(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        lblNewLabel = new JLabel("");
        
        JButton btnAttributesConfirm = new JButton("attributes confirm");
        btnAttributesConfirm.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		gett = true;
        		getField();
        		ok.setVisible(true);
        		jButton1.setVisible(true);
        		btnAttributesConfirm.setVisible(false);
        		
        	}
        });
        
        lblNewLabel_1 = new JLabel("");
        lblNewLabel_1.setFont(new Font("Tahoma", Font.BOLD, 13));
        
       
        
        
      

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(36)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 316, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(Name, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        									.addComponent(returnType, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        								.addComponent(accessModifier, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
        							.addGap(27)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(f1, GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        								.addComponent(f2)
        								.addComponent(f3)
        								.addComponent(ok)))
        						.addComponent(enterFiledDetails, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
        							.addComponent(btnAttributesConfirm)))
        					.addContainerGap())))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(enterFiledDetails, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Name)
        				.addComponent(f1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnAttributesConfirm))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(returnType)
        						.addComponent(f2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(f3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(accessModifier)
        						.addComponent(jButton1))))
        			.addGap(11)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(ok)
        				.addComponent(lblNewLabel_1))
        			.addGap(70))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    	dispGet();
    	lblNewLabel_1.setText("Get/Set method added");
    	jButton1.setVisible(false);
    	
    
    	
    	
    	
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void dispGet() {
    	String h = f1.getText();
       	String k = f2.getText();
    	String d = "public " + k + " get"+h+"() { ";
    	String e = "return " + h + "; }";
    	String m = "public void "  + " set"+h+"(" + k + " "+  " newAssign ) { ";
    	String l = "this." + h + " = newAssign ; }";
    	System.out.println(d);
    	System.out.println(e);
    	System.out.println(m);
    	System.out.println(l);
    	
    	
    	
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
       dispose();
    }
    
    public void getField() {
    	String f = f1.getText();
    	String g = f2.getText();
    	String h = f3.getText();
    	
    	String q = h + " " + g + " " + f + " ; ";
    	System.out.println(q);
    	
    	
    	
    	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterField().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel accessModifier;
    private javax.swing.JLabel enterFiledDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JButton ok;
    private javax.swing.JLabel returnType;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
}
