/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml.to.java;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Font;
import javax.swing.JTextField;
import java.awt.Color;

/**
 *
 * @author User
 */
public class ParentInterface extends javax.swing.JFrame {
	static String jk = "";
	static String parentinh = "";

    /**
     * Creates new form SelectClass
     */
    public ParentInterface() {
        initComponents();
    }
    
    public ParentInterface(String n ){
        initComponents();
        l1.setText(n+"");
    }
    
    /*public childInherit(String n,String i ){
        initComponents();
       // l2.setText(n+"");
        l1.setText(i+".1");
    }*/
    
    public void getCname () {
    	
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterName = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        next.setVisible(false);
        t1 = new javax.swing.JTextField();
        
        l1 = new javax.swing.JLabel();
        addClassField = new javax.swing.JButton();
        classMethod = new javax.swing.JButton();
        classMethod.setBackground(Color.CYAN);
        
     

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterName.setText("Enter Name :");

        next.setText("OK & EXIT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        addClassField.setText("Parent ClassField");
        addClassField.setVisible(false);
        addClassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassFieldActionPerformed(evt);
            }
        });

        classMethod.setText("Parent Class Method");
        classMethod.setVisible(false);
        classMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classMethodActionPerformed(evt);
            }
        });
        
        lblInheritanceChildClass = new JLabel("INTERFACE PARENT");
        lblInheritanceChildClass.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        btnConfirmName = new JButton("confirm name");
        btnConfirmName.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		/*if(t1.getText()=="rto") {
        			JOptionPane.showMessageDialog(null, "Name cannot be null ");
        		}
        		else {*/
        		next.setVisible(true);
        	getClassName();
        		lblNewLabel.setText("Interface Header Defined!");
        		 classMethod.setVisible(true);
        		addClassField.setVisible(true);
        		btnConfirmName.setVisible(false);
        		btnOpenImplementClass.setVisible(true);
        		lblallChangesSaved.setVisible(true);
        		enterName.setVisible(false);
        		t1.setVisible(false);}
        	}        );
        
        btnOpenImplementClass = new JButton("open child class");
        btnOpenImplementClass.setVisible(false);
        btnOpenImplementClass.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.out.println(" } ");
        		dispose();
        		childInterface frm=new  childInterface(l1.getText());
                frm.setVisible(true);
        	}
        });
        
        lblallChangesSaved = new JLabel("[All changes saved in parent class cannot be altered after this]");
        lblallChangesSaved.setVisible(false);
JLabel lblNewLabel_2 = new JLabel("");
lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        textField = new JTextField();
        textField.setColumns(10);
        //String sam = textField.getText();
        
        btnNewButton_1 = new JButton("Add Comment");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		System.out.println("/* "+ textField.getText()+ " */");
        		lblNewLabel_2.setText("Comment Added");
        		btnNewButton_1.setVisible(false);
        		textField.setVisible(false);
        		
        		
        		
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(layout.createSequentialGroup()
        						.addGap(45)
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(enterName, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        								.addGap(106)
        								.addComponent(t1, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
        								.addGap(80))
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(addClassField, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.UNRELATED)
        								.addComponent(next, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        								.addComponent(classMethod, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
        								.addGap(11))))
        					.addGroup(layout.createSequentialGroup()
        						.addGap(54)
        						.addComponent(l1, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createSequentialGroup()
        						.addGap(85)
        						.addComponent(lblInheritanceChildClass, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createSequentialGroup()
        						.addGap(190)
        						.addComponent(lblNewLabel)))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnOpenImplementClass)
        					.addGap(18)
        					.addComponent(lblallChangesSaved)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnConfirmName)
        					.addGap(65))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnNewButton_1)
        					.addGap(33))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(23))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(lblNewLabel_2)
        					.addGap(53))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(l1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblInheritanceChildClass))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnNewButton_1)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblNewLabel_2)))
        			.addGap(46)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(enterName)
        				.addComponent(btnConfirmName)
        				.addComponent(t1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(addClassField)
        				.addComponent(classMethod)
        				.addComponent(next))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnOpenImplementClass)
        				.addComponent(lblallChangesSaved))
        			.addGap(18))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

    String s = " } ";
    System.out.println(s);
        dispose();
    String name=t1.getText();
    //int idx=cb1.getSelectedIndex();
    //CLS a1=new CLS(name,idx);

        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void addClassFieldActionPerformed(java.awt.event.ActionEvent evt) {
    	parentinh=t1.getText();
    	jk = t1.getText();
    	//getClassName();
        interfaceField frm = new  interfaceField(l1.getText());
        frm.setVisible(true);       
    }

    
    
    private void classMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classMethodActionPerformed
    	parentinh=t1.getText();
    	//jk = t1.getText();
    	interfaceMethodNumber frm = new interfaceMethodNumber(l1.getText());
        frm.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_classMethodActionPerformed
    
    public void getClassName() {
    	
    	/*if(t1.getText()=="rto") {
    		JOptionPane.showMessageDialog(null, "Name cannot be null ");
    	}*/
    	
    	ParentInterface.jk = t1.getText();
    	String s = "interface  "+ t1.getText() + "  { ";
    	System.out.println(s);}
    	
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassField;
    private javax.swing.JButton classMethod;
    private javax.swing.JLabel enterName;
    private javax.swing.JLabel l1;
    public javax.swing.JButton next;
    public javax.swing.JTextField t1;
    private JLabel lblInheritanceChildClass;
    private JLabel lblNewLabel;
    private JButton btnConfirmName;
    private JButton btnOpenImplementClass;
    private JLabel lblallChangesSaved;
    private JButton btnNewButton_1;
    private JTextField textField;
    private JLabel lblNewLabel_2;
    // End of variables declaration//GEN-END:variables
}
