/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml.to.java;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class parentInherit extends javax.swing.JFrame {
	static String jk = "";
	static String parentinh = "";

    /**
     * Creates new form SelectClass
     */
    public parentInherit() {
        initComponents();
    }
    
    public parentInherit(String n ){
        initComponents();
        l1.setText(n+"");
    }
    
    /*public childInherit(String n,String i ){
        initComponents();
       // l2.setText(n+"");
        l1.setText(i+".1");
    }*/
    
    public void getCname () {
    	
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterName = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        next.setVisible(false);
        t1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        addClassField = new javax.swing.JButton();
        classMethod = new javax.swing.JButton();
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterName.setText("Enter Name :");

        next.setText("OK & EXIT");
        next.setVisible(false);
        
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        addClassField.setText("Parent ClassField");
        addClassField.setVisible(false);

        addClassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassFieldActionPerformed(evt);
            }
        });

        classMethod.setText("Parent Class Method");
        classMethod.setVisible(false);
        classMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classMethodActionPerformed(evt);
            }
        });
        
        lblInheritanceChildClass = new JLabel("INHERITANCE  PARENT CLASS");
        lblInheritanceChildClass.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        lblNewLabel = new JLabel("");
        
        btnConfirmName = new JButton("confirm name");
        btnConfirmName.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		parentInherit.parentinh= t1.getText();
        		next.setVisible(true);
        		t1.setVisible(false);
        		enterName.setVisible(false);
        		next.setVisible(true);
        		classMethod.setVisible(true);
        		addClassField.setVisible(true);
        		lblNewLabel.setText("Parent super class header defined!");
        		getClassName();
        		btnConfirmName.setVisible(false);
        		btnOpenChildClass.setVisible(true);
        		lblNewLabel_1.setVisible(true);
        	}
        });
        
        btnOpenChildClass = new JButton("Open child class");
        btnOpenChildClass.setVisible(false);
        btnOpenChildClass.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.out.println(" } ");
        		dispose();
        		childInherit frm2 = new childInherit(l1.getText());
                frm2.setVisible(true);
        	}
        });
        
        lblNewLabel_1 = new JLabel("[All changes saved in parent class cannot be altered after this]");
        lblNewLabel_1.setVisible(false);
        
JLabel lblNewLabel_2 = new JLabel("");
lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        textField = new JTextField();
        textField.setColumns(10);
        //String sam = textField.getText();
        
        btnNewButton_1 = new JButton("Add Comment");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		System.out.println("/* "+ textField.getText()+ " */");
        		lblNewLabel_2.setText("Comment Added");
        		btnNewButton_1.setVisible(false);
        		textField.setVisible(false);
        		
        		
        		
        	}
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(45)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(enterName, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        							.addGap(228))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(addClassField, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        							.addComponent(next, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        							.addGap(41)))
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(btnConfirmName)
        							.addGap(121))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(classMethod, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
        							.addGap(8))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(85)
        					.addComponent(lblInheritanceChildClass))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(54)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(l1, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE)
        						.addComponent(t1, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(176)
        					.addComponent(lblNewLabel))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(63)
        					.addComponent(btnOpenChildClass)
        					.addGap(18)
        					.addComponent(lblNewLabel_1)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(45)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnNewButton_1)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(37))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(lblNewLabel_2)
        					.addGap(70))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnNewButton_1)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblNewLabel_2)
        					.addGap(214))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(l1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblInheritanceChildClass)
        					.addGap(46)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(enterName)
        						.addComponent(t1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnConfirmName))
        					.addGap(26)
        					.addComponent(lblNewLabel)
        					.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(addClassField)
        						.addComponent(next)
        						.addComponent(classMethod))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnOpenChildClass)
        						.addComponent(lblNewLabel_1))
        					.addGap(18))))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

    
        String h = " } ";
        System.out.println(h);
    String name=t1.getText();
    dispose();
    //int idx=cb1.getSelectedIndex();
    //CLS a1=new CLS(name,idx);

        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void addClassFieldActionPerformed(java.awt.event.ActionEvent evt) {
    	parentinh=t1.getText();
    	jk = t1.getText();
    	//getClassName();
        ClassField frm = new ClassField(l1.getText());
        frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addClassFieldActionPerformed

    
    
    private void classMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classMethodActionPerformed
    	parentinh=t1.getText();
    	jk = t1.getText();
    	methodNumber frm = new methodNumber(l1.getText());
        frm.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_classMethodActionPerformed
    
    public void getClassName() {
    	
    	String s = "class  "+ t1.getText() + "  { ";
    	System.out.println(s);
    	
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parentInherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parentInherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parentInherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parentInherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parentInherit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassField;
    private javax.swing.JButton classMethod;
    private javax.swing.JLabel enterName;
    private javax.swing.JLabel l1;
    public javax.swing.JButton next;
    public javax.swing.JTextField t1;
    private JLabel lblInheritanceChildClass;
    private JLabel lblNewLabel;
    private JButton btnConfirmName;
    private JButton btnOpenChildClass;
    private JLabel lblNewLabel_1;
    private JButton btnNewButton_1;
    private JTextField textField;
    private JLabel lblNewLabel_2;
    // End of variables declaration//GEN-END:variables
}
