/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml.to.java;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class parentAbstract extends javax.swing.JFrame {
	static String jk = "";
	static String parentinh = "";

    /**
     * Creates new form SelectClass
     */
    public parentAbstract() {
    	setBackground(new Color(204, 0, 0));
        initComponents();
    }
    
    public parentAbstract(String n ){
        initComponents();
        l1.setText(n+"");
    }
    
    /*public childInherit(String n,String i ){
        initComponents();
       // l2.setText(n+"");
        l1.setText(i+".1");
    }*/
    
    public void getCname () {
    	
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterName = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        next.setVisible(false);
        t1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        addClassField = new javax.swing.JButton();
        classMethod = new javax.swing.JButton();
        classMethod.setBackground(new Color(102, 255, 255));
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterName.setText("Enter Name :");

        next.setText("OK & EXIT");
        next.setVisible(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        addClassField.setText("Parent ClassField");
        addClassField.setVisible(false);
        addClassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassFieldActionPerformed(evt);
            }
        });

        classMethod.setText("Parent Class Method");
        classMethod.setVisible(false);
        classMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classMethodActionPerformed(evt);
            }
        });
        
        lblInheritanceChildClass = new JLabel("ABSTRACT  PARENT CLASS");
        lblInheritanceChildClass.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        btnAbstactMethod = new JButton("abstract method");
   	 btnAbstactMethod.setVisible(false);
        btnAbstactMethod.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		parentAbstract.jk=t1.getText();
        		Abstractmethodnumber ab = new Abstractmethodnumber(l1.getText());
        		ab.setVisible(true);
        		
        	}
        });
        
        lblNewLabel = new JLabel("");
        
        btnConfirmName = new JButton("confirm name");
        btnConfirmName.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		next.setVisible(true);
        		btnNewButton.setVisible(true);
        		lblNewLabel_1.setVisible(true);
        		enterName.setVisible(false);
        		t1.setVisible(false);
        		getClassName();
        		lblNewLabel.setText("Parent Abstract header defined!");
        		 btnAbstactMethod.setVisible(true);
        		 classMethod.setVisible(true);
        		 addClassField.setVisible(true);
        		 next.setVisible(true);
        		 btnConfirmName.setVisible(false);
        	}
        });
        
        btnNewButton = new JButton("Open Child class");
        btnNewButton.setVisible(false);
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.out.println(" } ");
        		dispose();
        		childAbstract frm = new childAbstract(l1.getText());
                frm.setVisible(true);
        	}
        });
        
        lblNewLabel_1 = new JLabel("[All changes saved in parent class cannot be altered after this]");
        lblNewLabel_1.setVisible(false);
        
        JLabel lblNewLabel_2 = new JLabel("");
        lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        textField = new JTextField();
        textField.setColumns(10);
        //String sam = textField.getText();
        
        btnNewButton_1 = new JButton("Add Comment");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		System.out.println("/* "+ textField.getText()+ " */");
        		lblNewLabel_2.setText("Comment Added");
        		btnNewButton_1.setVisible(false);
        		textField.setVisible(false);
        		
        		
        		
        	}
        });
        
        
        
        
        
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(54)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblInheritanceChildClass)
        				.addComponent(l1, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(enterName, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        					.addGap(31)
        					.addComponent(t1, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(45)
        							.addComponent(btnConfirmName)
        							.addPreferredGap(ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
        							.addComponent(btnNewButton_1))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGap(91))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblNewLabel_2)
        					.addGap(118))))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(addClassField)
        					.addGap(16)
        					.addComponent(classMethod)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblNewLabel))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(25)
        							.addComponent(btnAbstactMethod)
        							.addGap(28)
        							.addComponent(next, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(204)
        					.addComponent(btnNewButton)
        					.addGap(28)
        					.addComponent(lblNewLabel_1)))
        			.addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnNewButton_1)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblNewLabel_2))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(l1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblInheritanceChildClass)
        					.addGap(46)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(t1, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        						.addComponent(enterName)
        						.addComponent(btnConfirmName))
        					.addGap(18)
        					.addComponent(lblNewLabel)
        					.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(addClassField)
        						.addComponent(classMethod)
        						.addComponent(btnAbstactMethod)
        						.addComponent(next))
        					.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnNewButton)
        						.addComponent(lblNewLabel_1))))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

    String j = " } ";
    System.out.println(j);
        
    String name=t1.getText();
    //int idx=cb1.getSelectedIndex();
    //CLS a1=new CLS(name,idx);

        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void addClassFieldActionPerformed(java.awt.event.ActionEvent evt) {
    	parentinh=t1.getText();
    	parentAbstract.jk = t1.getText();
    	//getClassName();
        ClassField frm = new ClassField(l1.getText());
        frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addClassFieldActionPerformed

    
    
    private void classMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classMethodActionPerformed
    	parentinh=t1.getText();
    	parentAbstract.jk = t1.getText();
    	methodNumber frm = new methodNumber(l1.getText());
        frm.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_classMethodActionPerformed
    
    public void getClassName() {
    	
    	String s = "abstact class  "+ t1.getText() + "  { ";
    	System.out.println(s);
    	
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parentAbstract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parentAbstract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parentAbstract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parentAbstract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parentAbstract().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassField;
    private javax.swing.JButton classMethod;
    private javax.swing.JLabel enterName;
    private javax.swing.JLabel l1;
    public javax.swing.JButton next;
    public javax.swing.JTextField t1;
    private JLabel lblInheritanceChildClass;
    private JButton btnAbstactMethod;
    private JLabel lblNewLabel;
    private JButton btnConfirmName;
    private JButton btnNewButton;
    private JLabel lblNewLabel_1;
    private JButton btnNewButton_1;
    private JTextField textField;
}
