/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml.to.java;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.sun.xml.internal.ws.api.pipe.NextAction;

import javax.swing.JCheckBox;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.SwingConstants;


/*jk = t1.getText();
getClassName();*/
/**
 *
 * @author User
 */
public class SelectClass extends javax.swing.JFrame {
	static String jk = "";

    /**
     * Creates new form SelectClass
     */
    public SelectClass() {
        initComponents();
    }
    
    public SelectClass(int n ){
        initComponents();
        l1.setText(n+"");
    }
    
    public SelectClass(String n,String i ){
        initComponents();
        l2.setText(n+"");
        l1.setText(i+"");
    }
    
    public void getCname () {
    	
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

       
        selectClassType = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        next = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t1.setVisible(false);
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        addClassField = new javax.swing.JButton();
        classMethod = new javax.swing.JButton();
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        enterName = new javax.swing.JLabel();
        

        selectClassType.setText("Select Class Type :");

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interface", "Normal", "Abstract", "Inheritance" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        next.setText("name confirm?");
        next.setVisible(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            
                nextActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setText("Select Class");

        addClassField.setText("ClassField");
        addClassField.setVisible(false);
        addClassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassFieldActionPerformed(evt);
            }
        });

        classMethod.setText("Class Method");
        classMethod.setVisible(false);
        classMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classMethodActionPerformed(evt);
            }
        });
        
        btnOkexit = new JButton("OK & EXIT");
        btnOkexit.setVisible(false);
        btnOkexit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String s = " } ";
        		System.out.println(s);
        		dispose();
        	}
        });
        
        lblNewLabel = new JLabel("Choose any one");
        
        lblNewLabel_1 = new JLabel("");
        lblNewLabel_1.setFont(new Font("Tahoma", Font.BOLD, 15));
        
        btnNewButton_1 = new JButton("Add Comment");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		System.out.println("/* "+ textField.getText()+ " */");
        		lblNewLabel_2.setText("Comment Added");
        		btnNewButton_1.setVisible(false);
        		textField.setVisible(false);
        	}
        });
        
        textField = new JTextField();
        textField.setColumns(10);
        btnNewButton_1.setVisible(false);
		textField.setVisible(false);
	
        
        lblNewLabel_2 = new JLabel("");
        lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblNewLabel_2.setVisible(false);
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(29)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(l2, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(l1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(enterName, GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(selectClassType, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
        							.addGap(29)
        							.addComponent(cb1, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblNewLabel)))))
        			.addGap(41)
        			.addComponent(btnNewButton_1)
        			.addGap(248))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(169)
        			.addComponent(btnOkexit)
        			.addContainerGap(848, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap(123, Short.MAX_VALUE)
        					.addComponent(t1, 78, 78, 78)
        					.addGap(98))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(46)
        					.addComponent(addClassField, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(classMethod, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(next)
        					.addGap(87)
        					.addComponent(lblNewLabel_1)
        					.addGap(173)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(318))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(761, Short.MAX_VALUE)
        			.addComponent(lblNewLabel_2)
        			.addGap(349))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(l2, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        						.addComponent(l1))
        					.addGap(24)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(cb1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        						.addComponent(selectClassType)
        						.addComponent(lblNewLabel))
        					.addGap(18)
        					.addComponent(enterName, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
        				.addComponent(btnNewButton_1))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(2)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(t1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(next, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(classMethod)
        								.addComponent(addClassField))
        							.addGap(223))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(btnOkexit)
        							.addGap(132))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(lblNewLabel_1)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblNewLabel_2)
        					.addContainerGap())))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
    	 addClassField.setVisible(true);
    	 enterName.setVisible(false);
    	 next.setVisible(false);
    	 t1.setVisible(false);
    	 classMethod.setVisible(true);
    	 btnOkexit.setVisible(true);
    	lblNewLabel_1.setText("Normal Class Header Defined!");
    	jk = t1.getText();
    	getClassName();
    	
    
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        if (cb1.getSelectedIndex() == 0){
        
        	 /*childInterface frm=new  childInterface(l1.getText());
             frm.setVisible(true);*/
        ParentInterface frm2=new  ParentInterface(l1.getText());
        frm2.setVisible(true);
        dispose();
        
        //frm.classMethod.setVisible(false);
        
        }
        if (cb1.getSelectedIndex() == 1){
        	enterName.setText("Enter  Class name");
        	 t1.setVisible(true);
        	next.setVisible(true);
        	 btnNewButton_1.setVisible(true);
     		textField.setVisible(true);
     	
            
             lblNewLabel_2.setVisible(true);
        	/* addClassField.setVisible(true);
        	 
        	 classMethod.setVisible(true);
        	 btnOkexit.setVisible(true);*/
        	
        }
        
        
        if (cb1.getSelectedIndex() == 2){
        	dispose();
           // t2.setEditable(true);
           
        	/*childAbstract frm = new childAbstract(l1.getText());
            frm.setVisible(true);*/
            
        parentAbstract frm2=new  parentAbstract(l1.getText());
        frm2.setVisible(true);
        
        //ImplementClass frm = new ImplementClass();
        //frm.setVisible(true);
        }

        if(cb1.getSelectedIndex() ==3){
        	dispose();
        	t1.setVisible(false);
        //t3.setEditable(true); 
        	/*childInherit frm2 = new childInherit(l1.getText());
            frm2.setVisible(true);*/
        parentInherit frm=new parentInherit(l1.getText());
        frm.setVisible(true);
        
       
        }    
    }

    private void addClassFieldActionPerformed(java.awt.event.ActionEvent evt) {
    	
        ClassField frm = new ClassField(l1.getText());
        frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addClassFieldActionPerformed

    
    
    private void classMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classMethodActionPerformed
    	jk = t1.getText();
    	methodNumber frm = new methodNumber(l1.getText());
        frm.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_classMethodActionPerformed
    
    public void getClassName() {
    	
    	String s = "class  "+ t1.getText() + "  { ";
    	System.out.println(s);
    	
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassField;
    public javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton classMethod;
    private javax.swing.JLabel enterName;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    public javax.swing.JButton next;
    private javax.swing.JLabel selectClassType;
    public javax.swing.JTextField t1;
    private JButton btnOkexit;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
    private JButton btnNewButton_1;
    private JTextField textField;
    private JLabel lblNewLabel_2;
    // End of variables declaration//GEN-END:variables
}
